name: Node.js Tests

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencias de prd
        run: npm install 
      - name: Install dependencias de dev
        run: npm install --save-dev
      - name: Run tests
        run: npm test
